const location = [
  'Bishan',
  'Bukit Merah',
  'Bukit Timah',
  'Downtown Core',
  'Geylang',
  'Kallang',
  'Marina East',
  'Marina South',
  'Marine Parade',
  'Museum',
  'Newton',
  'Novena',
  'Orchard',
  'Outram',
  'Queenstown',
  'River Valley',
  'Rochor',
  'Singapore River',
  'Southern Islands',
  'Straits View',
  'Tanglin',
  'Toa Payoh',
  'Bedok',
  'Changi',
  'Changi Bay',
  'Pasir Ris',
  'Paya Lebar',
  'Tampines',
  'Lim Chu Kang',
  'Mandai',
  'Sembawang',
  'Simpang',
  'Sungei Kadut',
  'Woodlands',
  'Yishun',
  'Ang Mo Kio',
  'Hougang',
  'Punggol',
  'Seletar',
  'Sengkang',
  'Serangoon',
  'Boon Lay',
  'Bukit Batok',
  'Bukit Panjang',
  'Choa Chu Kang',
  'Clementi',
  'Jurong East',
  'Jurong West',
  'Pioneer',
  'Tengah',
  'Tuas',
  'Western Islands',
  'Western Water Catchment'
];

export default location;
